#' Generate sample matrices
#'
#' @description Generates a set of matrices for use in the search functions.
#'
#' @details This is a helper function that generates 3 matrices to be used in the search functions in this package.
#' The function will assign 3 numeric functions to the global environment: "prior_grid", "pod_grid" and "cost_grid".
#' "prior_grid" is a normalized matrix of value generated by the \link[MASS]{kde2d} function from the MASS package.
#' Both "pod_grid" and "cost_grid" are random values sampled from the Uniform(0,1) distribution.
#'
#'
#' @param n An integer representing the number of rows and columns for the square matrices
#'
#' @return 3 x Numeric matrix
#'
#' @examples generate_sample_matrix(5)
#'
#' @import MASS
#' @import stats
#' @export
#'
generate_sample_matrix <- function(n){
  x_prior <- rnorm(n^2)
  y_prior <- rnorm(n^2)
  prior_kde <- MASS::kde2d(x_prior,y_prior,n=n)
  prior_matrix <- create_prior_grid(prior_kde$z)
  assign("prior_grid",prior_matrix, envir = .GlobalEnv)

  pod_matrix <- matrix(stats::runif(n^2, min = 0, max = 1), nrow = n, ncol = n)
  assign("pod_grid",pod_matrix, envir = .GlobalEnv)

  cost_matrix <- matrix(stats::runif(n^2, min = 0, max = 1), nrow = n, ncol = n)
  assign("cost_grid",cost_matrix, envir = .GlobalEnv)

}


