# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Create a prior grid
#'
#' @description 'create_prior_grid' returns a valid prior from a given numeric matrix
#'
#' @details This is a function that takes any numeric matrix and returns another numeric matrix which is a valid probability
#' density function that has a "prior" attribute assigned to it. The input doesn't have to be a valid PDF the function will
#' do this so when using this package its always good to use this function before using any of the search functions.
#'
#' @param prior_input A numeric matrix
#'
#' @returns A (normalized) numeric matrix
#'
#' @examples create_prior_grid(matrix(c(1,2,3,4),nrow = 1, ncol = 4))
#'
#'
#' @export
create_prior_grid <- function(prior_input) {
    .Call(`_BayesSearch_create_prior_grid`, prior_input)
}

#' Calculate the posterior distribution
#'
#' @description Calculate the posterior distribution after a negative search of a given grid square
#'
#' @details This function will calculate the posterior distribution from a given prior matrix, probability of detection matrix
#' and a column and row index.
#'
#' @param prior_grid A numeric matrix that is a valid probability density function. Use \code{\link{create_prior_grid}} for validation.
#'
#' @param pod_grid A numeric matrix. All matrix entries must be greater than 0 and less than 1.
#'
#' @param row Integer representing the row index
#'
#' @param col Integer representing the column index
#'
#' @returns Numeric matrix
#'
#' @examples update_posterior_neg(prior_grid, pod_grid, 1, 1)
#'
#' @export
update_posterior_neg <- function(prior_grid, pod_grid, row, col) {
    .Call(`_BayesSearch_update_posterior_neg`, prior_grid, pod_grid, row, col)
}

